In [5]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([4,5,6])

In [12]:
d = np.vstack((a,b,c))
d

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [9]:
vals, vecs = np.linalg.eig(d)

In [10]:
vals

array([ 1.27082039e+01, -7.08203932e-01, -2.65381787e-17])

In [11]:
vecs

array([[ 0.28907816,  0.90041255,  0.40824829],
       [ 0.67691721, -0.30761765, -0.81649658],
       [ 0.67691721, -0.30761765,  0.40824829]])

In [13]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [17]:
s=np.zeros((3,3))

In [18]:
print(s.ravel())

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
print(s.reshape((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
np.random.random() #[0.0,1)

0.7161424704940292

In [22]:
np.random.randint(1,10)

4

In [23]:
np.random.rand(5)

array([0.98523555, 0.41838398, 0.28754779, 0.71622218, 0.68038258])

In [25]:
np.random.rand(2,3)

array([[0.25597841, 0.17661603, 0.73158508],
       [0.82895755, 0.40009591, 0.07694004]])

In [27]:
a=np.array(range(10))
np.random.shuffle(a)
a

array([1, 3, 0, 5, 4, 8, 9, 7, 6, 2])

In [28]:
# dot product
dot_first = np.array([1,2,29])
dot_second = np.array([2,0,9])
print(np.dot(dot_first, dot_second))


263


In [29]:
# linespace
# say the range is 0-10 we need 5 values in between them
equally_spaced_values = np.linspace(0, 10, 5)
print(equally_spaced_values)

[ 0.   2.5  5.   7.5 10. ]


In [33]:
# empty
# used to create an numpy array with zeros of specified size
zero_array = np.empty((3, 2))
zero_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
# Concatenate
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [38]:
# Sum 
print(np.sum(c))
a = np.array([[1,2,3],[4,5,6]])
np.sum(a,axis=0)

21


array([5, 7, 9])

In [39]:
a = np.arange(12).reshape(2,2,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [46]:
a = np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [48]:
a[:,np.newaxis]

array([[[1]],

       [[2]],

       [[3]]])

In [49]:
a = np.array([[1,4,9]])
np.sqrt(a)

array([[1., 2., 3.]])

In [52]:
np.insert(a,2,8)

array([1, 4, 8, 9])

In [60]:
a=[[1,2,3],[3,4,5]]
np.delete(a,[5])

array([1, 2, 3, 3, 4])

In [61]:
c=np.array([1,2,3,4,5,6])
np.hsplit(c,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [62]:
d=np.array([[1,2,3],[4,5,6]])
np.vsplit(d,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [63]:
e=np.array([4,7,2,6,1])
np.sort(e)

array([1, 2, 4, 6, 7])

In [64]:
f=np.arange(10,25,5)
f

array([10, 15, 20])

In [65]:
a= np.array([1,2,3])
b=a
c=a.copy()
a[0]=7

print(b)
print(c)


[7 2 3]
[1 2 3]


In [66]:
a=np.array([1,2,3,4,5,6,7])
indices=[2,5,8]

splitArray=np.split(a,indices)
splitArray

[array([1, 2]), array([3, 4, 5]), array([6, 7]), array([], dtype=int32)]

In [67]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.append(a,b)

c

array([1, 2, 3, 4, 5, 6])

In [68]:
a= np.array([6,5,2,-1,0],float)
a.clip(0,5)

array([5., 5., 2., 0., 0.])

In [69]:
b = np.array([1,2,4,4,6,6,9,8,8],float)
np.unique(b)

array([1., 2., 4., 6., 8., 9.])

In [70]:
c= np.array([[1,2],[3,4],[5,6]])
c.diagonal()

array([1, 4])

In [71]:
d=np.array([1,3,0,4])
np.logical_and(d>0, d<3)

array([ True, False, False, False])

In [73]:
arr1=np.array([1,2,3,4])
print(np.square(arr1))

[ 1  4  9 16]


In [74]:
arr2=np.copy(arr1)
print(np.array_equal(arr1,arr2))

True


In [75]:
print(np.power(arr1,arr2))

[  1   4  27 256]


In [76]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [77]:
print(np.median(arr1))

2.5


In [79]:
print(np.mean(arr1))

2.5


In [80]:
np.matmul(arr1,arr2)

30

In [84]:
a1 = np.array([[1,2,3],[3,4,5]],float)

In [85]:
U, s, Vh = np.linalg.svd(a1)

In [86]:
U

array([[-0.46410668,  0.88577931],
       [-0.88577931, -0.46410668]])

In [87]:
s

array([7.97638869, 0.61418515])

In [88]:
Vh

array([[-0.39133557, -0.5605708 , -0.72980603],
       [-0.8247362 , -0.13817999,  0.54837623],
       [ 0.40824829, -0.81649658,  0.40824829]])

In [90]:
a=np.array([3,1,2])
indices=np.argsort(a)
print(indices)

[1 2 0]


In [91]:
np.savetxt("array.txt",U)

In [92]:
d=np.genfromtxt("array.txt")

In [93]:
d

array([[-0.46410668,  0.88577931],
       [-0.88577931, -0.46410668]])

In [94]:
a =np.array([[0,1],[3,0]])
a.nonzero()


(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

In [96]:
a= np.array([0,1,2,3,4,5])
b=np.array([9,8,7])
a.put([0,3],b)
a

array([9, 1, 2, 8, 4, 5])

In [97]:
np.roots([1,-3,2])

array([2., 1.])

In [99]:
a=np.array([3,4,5])
b=np.array([9,7,8])
np.column_stack((a,b))

array([[3, 9],
       [4, 7],
       [5, 8]])

In [100]:
a=np.array([1,2,3,4,5])
cum_sum=np.cumsum(a)
cum_sum

array([ 1,  3,  6, 10, 15])

In [104]:
# Squueze
a = np.array([[[1],[2],[3]]])
print(a.shape)
print(np.squeeze(a).shape)
print(np.squeeze(a,axis=0).shape)

(1, 3, 1)
(3,)
(3, 1)


In [106]:
# Roll 
a = np.array([1,2,3,4,5])
np.roll(a,-2)

array([3, 4, 5, 1, 2])

In [107]:
np.where(a <4, a, 10*a)


array([ 1,  2,  3, 40, 50])

In [108]:
b = np.array([2,3,4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6])

In [109]:
a=np.array([[1,2],[2,3],[3,4]])
for index,value in np.ndenumerate(a):
    print(index,value)

(0, 0) 1
(0, 1) 2
(1, 0) 2
(1, 1) 3
(2, 0) 3
(2, 1) 4


In [110]:
a=np.array([1,2,0,-1,-2,-3,4])
mask_array=np.ma.masked_array(a,mask=a<0)
print(mask_array)

[1 2 0 -- -- -- 4]


In [112]:
a=np.array([1,3,5,6,7])
np.partition(a,3)

array([3, 1, 5, 6, 7])

In [113]:
a=np.array([1,3,0],float)
any(a<2)

True

In [114]:
a=np.array([1,3,0],float)
all(a<2)

False

In [116]:
a=np.array([1,2,3,4,5])
np.take(a,[1,3])

array([2, 4])

In [117]:
a=np.array([1,3,4,7])
np.searchsorted(a,2)

1

In [119]:
a=np.array([1,2,3,4,5])
test_elements=np.array([2,3,5])
result=np.isin(a,test_elements)
result

array([False,  True,  True, False,  True])